In [154]:
import pandas as pd
import numpy as np
import math
from datetime import datetime, timedelta

In [155]:
student = pd.read_csv('student.csv')

In [156]:
df = pd.DataFrame(student)

In [157]:
df.shape

(20, 10)

In [158]:
df.head()

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27

##เทคนิคการจัดการข้อมูลพื้นฐาน

 *การจัดการข้อมูลหาย*

ลบแถวที่มีค่าหาย

In [159]:
# เหมาะเมื่อมีข้อมูลหายน้อย - ลบแถวที่มี NaN (ค่าหาย)
df_clean = df.dropna()

In [160]:
# DataFrame ใหม่ที่ลบ NaN (ค่าหาย) ออกแล้ว
df_clean

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24

เติมค่าด้วยค่าเฉลี่ย

In [161]:
#หาค่าเฉลี่ยของคอลัมน์อายุ
mean_age = df['อายุ'].mean()

In [162]:
mean_age

np.float64(28.470588235294116)

In [163]:
#เติมค่า 28.470588 ลงในช่องที่เป็น NaN (ของ 64003, ธีระ, รัตนา)
df['อายุ'] = df['อายุ'].fillna(mean_age)

In [164]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,28.470588,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.000000,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.000000,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,28.470588,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.000000,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.000000,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.000000,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.000000,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

เติมค่าด้วยค่าที่พบบ่อยที่สุด

In [165]:
#หาค่าที่พบบ่อยที่สุด (Mode) ในคอลัมน์คณะ ในนี้จะเป็น Science และจะเติม 'Science' ลงในช่องที่เป็น NaN (ของธีระ, ยุพา)
df['คณะ'].fillna(df['คณะ'].mode()[0], inplace=True)

/tmp/ipython-input-794965548.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['คณะ'].fillna(df['คณะ'].mode()[0], inplace=True)

In [166]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,28.470588,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.000000,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.000000,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,28.470588,NaN,Science,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.000000,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.000000,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.000000,หญิง,Science,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.000000,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

การทำให้ข้อมูลเป็นมาตรฐาน

In [167]:
#ทำให้ชื่อคณะเป็นมาตรฐานเดียวกัน
def standardize_faculty(name):
    if name in ['วิทยาศาสตร์', 'วิทย์', 'Science', 'คณะวิทยาศาสตร์', 'Sci']:
        return 'วิทยาศาสตร์'
    elif name in ['ศิลปศาสตร์', 'ศิลป์', 'Arts', 'Liberal Arts']:
        return 'ศิลปศาสตร์'
    elif name in ['วิศวฯ', 'วิศวะ', 'วิศวกรรม', 'Engineering']:
        return 'วิศวกรรมศาสตร์'
    else:
        return name

In [168]:
#สร้างคอลัมน์ใหม่ที่เก็บชื่อคณะที่เป็นมาตรฐานแล้ว
df['คณะ_มาตรฐาน'] = df['คณะ'].apply(standardize_faculty)

In [169]:
df['คณะ_มาตรฐาน']

0        วิทยาศาสตร์
1        วิทยาศาสตร์
2        วิทยาศาสตร์
3        วิทยาศาสตร์
4     วิศวกรรมศาสตร์
5     วิศวกรรมศาสตร์
6     วิศวกรรมศาสตร์
7         ศิลปศาสตร์
8         ศิลปศาสตร์
9         ศิลปศาสตร์
10       วิทยาศาสตร์
11       วิทยาศาสตร์
12    วิศวกรรมศาสตร์
13        ศิลปศาสตร์
14       วิทยาศาสตร์
15       วิทยาศาสตร์
16    วิศวกรรมศาสตร์
17       วิทยาศาสตร์
18        ศิลปศาสตร์
19       วิทยาศาสตร์
Name: คณะ_มาตรฐาน, dtype: object

การจัดการค่าผิดปกติ

In [170]:
print(f"\nค่าเฉลี่ยอายุ (รวมค่าผิดปกติ) - {df['อายุ'].mean():.2f}")

ค่าเฉลี่ยอายุ (รวมค่าผิดปกติ) - 28.47

In [171]:
#หาค่า Quartile ที่ 1 และ หาค่า Quartile ที่ 3
Q1 = df['อายุ'].quantile(0.25)
Q3 = df['อายุ'].quantile(0.75)

In [172]:
Q1, Q3

(np.float64(20.0), np.float64(22.25))

In [173]:
#Interquartile Range คือช่วงระหว่าง Q1 และ Q3 บอกถึงการกระจายตัวของข้อมูลส่วนกลาง 50%
IQR = Q3 - Q1

In [174]:
IQR

np.float64(2.25)

In [175]:
#กำหนดขอบเขต
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [176]:
lower_bound, upper_bound

(np.float64(16.625), np.float64(25.625))

In [177]:
#กรองค่าผิดปกติ
df_no_outliers = df[(df['อายุ'] >= lower_bound) & (df['อายุ'] <= upper_bound)]

In [178]:
df_no_outliers

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,คณะ_มาตรฐาน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23,วิทยาศาสตร์
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05,วิทยาศาสตร์
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30,วิทยาศาสตร์
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27,วิศวกรรมศาสตร์
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05,วิศวกรรมศาสตร์
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23,ศิลปศาสตร์
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11,ศิลปศาสตร์
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03,ศิลปศาสตร์
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26,วิทยาศาสตร์
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26,วิศวกรรมศาสตร์
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08,ศิลปศาสตร์
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06,วิทยาศาสตร์
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20,วิทยาศาสตร์
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24,วิศวกรรมศาสตร์
17,64018,ยุพา,21.0,หญิง,Science,3.23,161.0,50.0,27.0,2024-01-08,วิทยาศาสตร์
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06,วิทยาศาสตร์

In [179]:
#กรองเฉพาะแถวที่มีอายุอยู่ในช่วงที่กำหนด
(df['อายุ'] >= lower_bound) & (df['อายุ'] <= upper_bound)

0      True
1      True
2     False
3      True
4      True
5     False
6      True
7      True
8      True
9      True
10    False
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18    False
19     True
Name: อายุ, dtype: bool

##Feature Engineering

One-Hot Encoding แปลงข้อมูลประเภทเป็นตัวเลข

In [180]:
data = pd.DataFrame(student)

In [181]:
#แปลงคอลัมน์คณะเป็น  One-Hot Encoding
data_encoded = pd.get_dummies(data, columns=['คณะ'])
print(data_encoded)

    รหัสนักศึกษา      ชื่อ   อายุ     เพศ   GPA  ส่วนสูง_cm  น้ำหนัก_kg  \
0          64001     สมชาย   20.0     ชาย  3.21       170.0        65.0
1          64002    สมหญิง   21.0    หญิง  3.45       165.0        58.0
2          64003       NaN    NaN    Male  3.67       175.0         NaN
3          64004  สมศักดิ์   22.0       ช -1.00       168.0        70.0
4          64005      สมใจ   19.0       ญ  3.89       160.0        52.0
5          64006     กานต์  150.0     ชาย  3.12       172.0        75.0
6          64007     กิตติ   21.0    หญิง  4.50       158.0        48.0
7          64008      จิรา   20.0       F  2.98       180.0        82.0
8          64009    ชนาธิป   23.0       M  3.34       163.0        55.0
9          64010      ดารา   21.0    หญิง  3.56       167.0        60.0
10         64011      ธีระ    NaN     NaN  3.78         NaN        68.0
11         64012       นภา   22.0     ชาย   NaN       171.0         NaN
12         64013     บุญมี   20.0    หญิง  3.23       169.0        72.0
13         64014     ปรีชา   21.0     ชาย  3.45       164.0        54.0
14         64015     พิมพ์   22.0  Female  3.67       162.0        56.0
15         64016      ภูมิ   19.0       ช  3.89       173.0        78.0
16         64017      มานี   20.0       ญ  3.01       166.0        62.0
17         64018      ยุพา   21.0    หญิง  3.23       161.0        50.0
18         64019     รัตนา    NaN     ชาย   NaN       174.0        76.0
19         64020     ลัดดา   22.0     NaN  3.45       168.0        64.0

    ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน  คณะ_Arts  ...  คณะ_Science  \
0                      15.0      2024-01-23     False  ...        False
1                      20.0      2024-02-05     False  ...        False
2                      25.0      2024-01-13     False  ...         True
3                      10.0      2023-12-30     False  ...        False
4                      30.0      2024-01-27     False  ...        False
5                      12.0      2023-12-23     False  ...        False
6                      35.0      2024-01-05     False  ...        False
7                      18.0      2024-01-23     False  ...        False
8                      22.0      2024-02-11      True  ...        False
9                      28.0      2024-01-03     False  ...        False
10                      NaN      2024-01-07     False  ...         True
11                     16.0      2023-12-26     False  ...        False
12                     24.0      2023-12-26     False  ...        False
13                     19.0      2024-01-08     False  ...        False
14                     26.0      2024-02-06     False  ...        False
15                     14.0      2024-01-20     False  ...        False
16                     21.0      2024-01-24     False  ...        False
17                     27.0      2024-01-08     False  ...         True
18                      NaN      2023-12-18     False  ...        False
19                     23.0      2024-01-06     False  ...         True

    คณะ_คณะวิทยาศาสตร์  คณะ_วิทยาศาสตร์  คณะ_วิทย์  คณะ_วิศวกรรม  \
0                False             True      False         False
1                False            False       True         False
2                False            False      False         False
3                 True            False      False         False
4                False            False      False         False
5                False            False      False         False
6                False            False      False          True
7                False            False      False         False
8                False            False      False         False
9                False            False      False         False
10               False            False      False         False
11               False            False       True         False
12               False            False      False         False
13               False            False      False         False
14               False            False      False         False
15               False             True      False         False
16               False            False      False         False
17               False            False      False         False
18               False            False      False         False
19               False            False      False         False

    คณะ_วิศวกรรมศาสตร์  คณะ_วิศวฯ  คณะ_วิศวะ  คณะ_ศิลปศาสตร์  คณะ_ศิลป์
0                False      False      False           False      False
1                False      False      False           False      False
2                False      False      False           False      False
3                False      False      False           False      False
4                False      False       True           False      False
5                False      False      False           False      False
6                False      False      False           False      False
7                False      False      False            True      False
8                False      False      False           False      False
9                False      False      False           False       True
10               False      False      False           False      False
11               False      False      False           False      False
12               False       True      False           False      False
13               False      False      False           False      False
14               False      False      False           False      False
15               False      False      False           False      False
16                True      False      False           False      False
17               False      False      False           False      False
18               False      False      False            True      False
19               False      False      False           False      False

[20 rows x 23 columns]

การสร้าง Feature จากวันเวลา

In [182]:
data['วันที่ลงทะเบียน'] = pd.to_datetime(data['วันที่ลงทะเบียน'])
data['วันในสัปดาห์'] = data['วันที่ลงทะเบียน'].dt.day_name()
data

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,วันในสัปดาห์
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23,Tuesday
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05,Monday
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13,Saturday
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30,Saturday
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27,Saturday
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23,Saturday
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05,Friday
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23,Tuesday
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11,Sunday
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03,Wednesday
10,64011,ธีระ,NaN,NaN,Science,3.78,NaN,68.0,NaN,2024-01-07,Sunday
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26,Tuesday
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26,Tuesday
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08,Monday
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06,Tuesday
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20,Saturday
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24,Wednesday
17,64018,ยุพา,21.0,หญิง,Science,3.23,161.0,50.0,27.0,2024-01-08,Monday
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18,Monday
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06,Saturday

การรวม Features

In [183]:
#สร้าง BMI
data['BMI'] = data['น้ำหนัก_kg'] / (data['ส่วนสูง_cm']/100)**2

In [184]:
data

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,วันในสัปดาห์,BMI
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23,Tuesday,22.491349
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05,Monday,21.303949
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13,Saturday,NaN
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30,Saturday,24.801587
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27,Saturday,20.312500
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23,Saturday,25.351541
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05,Friday,19.227688
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23,Tuesday,25.308642
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11,Sunday,20.700817
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03,Wednesday,21.513859
10,64011,ธีระ,NaN,NaN,Science,3.78,NaN,68.0,NaN,2024-01-07,Sunday,NaN
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26,Tuesday,NaN
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26,Tuesday,25.209201
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08,Monday,20.077335
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06,Tuesday,21.338211
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20,Saturday,26.061679
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24,Wednesday,22.499637
17,64018,ยุพา,21.0,หญิง,Science,3.23,161.0,50.0,27.0,2024-01-08,Monday,19.289379
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18,Monday,25.102391
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06,Saturday,22.675737

In [185]:
data['สุขภาพ'] = pd.cut(data['BMI'],
                                   bins=[0, 18.5, 25, 30, 100],
                                   labels=['ผอม', 'ปกติ', 'อ้วน', 'อ้วนมาก'])

In [186]:
data

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,วันในสัปดาห์,BMI,สุขภาพ
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23,Tuesday,22.491349,ปกติ
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05,Monday,21.303949,ปกติ
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13,Saturday,NaN,NaN
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30,Saturday,24.801587,ปกติ
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27,Saturday,20.312500,ปกติ
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23,Saturday,25.351541,อ้วน
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05,Friday,19.227688,ปกติ
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23,Tuesday,25.308642,อ้วน
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11,Sunday,20.700817,ปกติ
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03,Wednesday,21.513859,ปกติ
10,64011,ธีระ,NaN,NaN,Science,3.78,NaN,68.0,NaN,2024-01-07,Sunday,NaN,NaN
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26,Tuesday,NaN,NaN
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26,Tuesday,25.209201,อ้วน
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08,Monday,20.077335,ปกติ
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06,Tuesday,21.338211,ปกติ
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20,Saturday,26.061679,อ้วน
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24,Wednesday,22.499637,ปกติ
17,64018,ยุพา,21.0,หญิง,Science,3.23,161.0,50.0,27.0,2024-01-08,Monday,19.289379,ปกติ
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18,Monday,25.102391,อ้วน
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06,Saturday,22.675737,ปกติ